# Generated by Django 5.2.8 on 2026-04-16 06:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterModelOptions(
            name='auteur',
            options={},
        ),
        migrations.AlterModelOptions(
            name='livre',
            options={},
        ),
        migrations.RemoveField(
            model_name='auteur',
            name='biographie',
        ),
        migrations.RemoveField(
            model_name='auteur',
            name='date_creation',
        ),
        migrations.RemoveField(
            model_name='livre',
            name='categorie',
        ),
        migrations.RemoveField(
            model_name='livre',
            name='date_creation',
        ),
        migrations.AlterField(
            model_name='auteur',
            name='nationalite',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='auteur',
            name='nom',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='livre',
            name='annee_publication',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='livre',
            name='auteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.auteur'),
        ),
        migrations.AlterField(
            model_name='livre',
            name='isbn',
            field=models.CharField(max_length=13, unique=True),
        ),
        migrations.AlterField(
            model_name='livre',
            name='titre',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='Emprunt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_emprunt', models.DateField(auto_now_add=True)),
                ('rendu', models.BooleanField(default=False)),
                ('livre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.livre')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='livre',
            name='tags',
            field=models.ManyToManyField(blank=True, to='api.tag'),
        ),
    ]
