# Generated by Django 5.2.8 on 2026-04-16 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_auteur_id_alter_emprunt_id_alter_livre_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etiquette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='livre',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='auteur',
            name='nationalite',
        ),
        migrations.RemoveField(
            model_name='emprunt',
            name='utilisateur',
        ),
        migrations.RemoveField(
            model_name='livre',
            name='disponible',
        ),
        migrations.RemoveField(
            model_name='livre',
            name='isbn',
        ),
        migrations.AddField(
            model_name='emprunt',
            name='date_retour',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='livre',
            name='annee_publication',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='livre',
            name='etiquettes',
            field=models.ManyToManyField(blank=True, to='api.etiquette'),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
